import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/header";
import ElectionFeed from "../components/election-feed";

const Elections: NextPage = () => {
  return (
    <div className="bg-gray-50-h-screen overflow-y-scroll scrollbar-hide">
      <Head>
        <title>Productive</title>
        <meta
          name="Congress Voting Data Platform"
          content="Generated by Productive"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <div className="mb-16">
        <Header message={"Productive"} />
      </div>
      <ElectionFeed message="Midterm Senate Elections" />
    </div>
  );
};

export default Elections;
